#Preguntar si todas las operaciones tienen que llevar el error 500, la 204 si tiene que responder con algo y cuando hay que utilizar el error
#400 y cuando el 404. El 404 es para el post y put cuando no se pone un campo obligatorio. Añadir a los errores mensajes abajo
openapi: 3.0.1
info:
  title: Cine API
  description: API para la gestión de cines
  version: 1.0.0
servers:
  - url: 'https://api.tucine.com'
tags:
  - name: showtime
    description: Operaciones para gestionar las funciones de películas
  - name: users
    description: Operaciones para gestionar los usuarios de la aplicacion
  - name: booking
    description: Gestión de reservas para ver funciones por parte de los usuarios
  - name: movie
    description: Gestión de las películas disponibles en el cine
  - name: cinema
    description: Gestión del cine
paths:
  /showtime:
    get:
      tags:
        - showtime
      summary: Listado de funciones de películas.
      description: Esta operación permite consultar el listado completo de funciones con toda su información.
      parameters:
        - name: screenName
          in: query
          description: Número de sala de la función
          required: true
          schema:
            type: number
            format: int32
            example: 1
        - name: price
          in: query
          description: Precio de la función
          required: true
          schema:
            type: number
            format: int32
            example: 7
        - name: isSoldOut
          in: query
          description: Entradas vendidas o no (Boolean)
          required: true
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: Devuelve la lista completa de funciones registradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShowtimeOut'
              examples:
                showtime1:
                  value:
                    - id: 1
                      screenNumber: 1
                      startTime: "2023-01-01T10:00:00Z"
                      price: 7
                      isSoldOut: false
                      endTime: 2023-01-01T12:00:00Z
                showtime2:
                  value:
                    - id: 2
                      screenNumber: 2
                      startTime: "2023-01-01T14:00:00Z"
                      price: 8
                      isSoldOut: true
                      endTime: "2023-01-01T16:00:00Z"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      tags:
        - showtime
      summary: Registrar una nueva funcion
      operationId: postShowtime
      requestBody:
        description: Información de la nueva función
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowtimeIn'
            examples:
              showtime1:
                value:
                  screenNumber: 3
                  startTime: "2023-01-01T18:00:00Z"
                  price: 9
                  isSoldOut: false
                  endTime: "2023-01-01T20:00:00Z"
      responses:
        '201':
          description: Función registrada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowtimeOut'
              examples:
                showtime2:
                  value:
                    id: 3
                    screenNumber: 3
                    startTime: "2023-01-01T18:00:00Z"
                    price: 9
                    isSoldOut: false
                    endTime: "2023-01-01T20:00:00Z"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      tags:
        - showtime
      summary: Dar de baja una función
      operationId: deleteShowtime
      parameters:
        - name: showtimeId
          in: path
          description: Identificador de la función
          required: true
          schema:
            type: number
            format: int32
            example: 1
      responses:
        '204':
          description: Ok
        '404':
          description: No se ha encontrado la función
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar esta función"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    put:
      tags:
        - showtime
      summary: Modifica una función
      description: Modifica los datos de una función concreta
      operationId: modifyShowtime
      parameters:
        - name: showtimeId
          in: path
          description: Identificador de la función
          required: true
          schema:
            type: number
            format: int32
            example: 1
      requestBody:
        description: Datos de función actualizados
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowtimeIn'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowtimeOut'
        '404':
          description: No se ha encontrado esta función
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar la función"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /users:
    get:
      tags:
        - users
      summary: Listado de usuarios.
      description: Esta operación permite consultar el listado completo de usuarios con toda su información.
      parameters:
        - name: username
          in: query
          description: Nombre de usuario
          required: true
          schema:
            type: string
            example: Daniel
        - name: email
          in: query
          description: Correo electrónico del usuario
          required: true
          schema:
            type: string
            example: sahashae@gmail.com
        - name: phone
          in: query
          description: Teléfono del usuario
          required: true
          schema:
            type: number
            format: int32
            example: 675908432
      responses:
        '200':
          description: Devuelve la lista completa de usuarios registrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserOut'
              examples:
                user1:
                  value:
                    - id: 1
                      username: "Daniel"
                      email: "sahashae@gmail.com"
                      phone: 675908432
                      registrationDate: "2023-01-01"
                user2:
                  value:
                    - id: 2
                      username: "OtroUsuario"
                      email: "otrousuario@gmail.com"
                      phone: 123456789
                      registrationDate: "2023-01-02"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      tags:
        - users
      summary: Registrar un nuevo usuario
      operationId: postUser
      requestBody:
        description: Información del nuevo usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIn'
      responses:
        '201':
          description: Usuario registrado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOut'
              examples:
                user1:
                  value:
                    - id: 3
                      username: "NuevoUsuario"
                      password: "contraseña"
                      email: "nuevousuario@gmail.com"
                      phone: 987654321
                      registrationDate: "2023-01-03"
                user2:
                  value:
                    - id: 5
                      username: "Daniek"
                      password: "AJDNNADW"
                      email: "daniel@gmail.com"
                      phone: 987654321
                      registrationDate: "2023-01-03"

        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      tags:
        - users
      summary: Dar de baja a un usuario
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: Identificador del usuario
          required: true
          schema:
            type: number
            format: int32
            example: 1
      responses:
        '204':
          description: Ok
        '404':
          description: No se ha encontrado al usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar este usuario"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    put:
      tags:
        - users
      summary: Modifica un usuario
      description: Modifica los datos de un usuario concreto
      operationId: modifyUser
      parameters:
        - name: userId
          in: path
          description: Identificador del usuario
          required: true
          schema:
            type: number
            format: int32
            example: 1
      requestBody:
        description: Datos de usuario actualizados
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIn'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserOut'
        '404':
          description: No se ha encontrado este usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar el usuario"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /booking:
    get:
      tags:
        - booking
      summary: Listado de reservas.
      description: Esta operación permite consultar el listado completo de reservas con toda su información.
      parameters:
        - name: id
          in: query
          description: Id de la reserva
          required: true
          schema:
            type: number
            format: int32
            example: 1
        - name: number
          in: query
          description: Numero asociado a la reserva
          required: true
          schema:
            type: number
            format: int64
            example: 7abc9c42-cba3-4ca8-8062-680edce11b8e
        - name: bookingDate
          in: query
          description: Fecha de la reserva
          required: true
          schema:
            type: number
            format: 'date-time'
            example: 2023-11-23T12:36:53.69
      responses:
        '200':
          description: Devuelve la lista completa de películas registradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookingOut'
              examples:
                booking1:
                  value:
                    - id: 1
                      number: "0b1e3747-3c24-4627-aafb-fdbec47947f7"
                      row: 3
                      bookingDate: "2023-12-13T20:41:59.437482"
                      seat: 10
                      menu: false
                booking2:
                  value:
                    - id: 2
                      number: "ed5dbf59-9680-4103-add7-34e2333d2e65"
                      row: 7
                      bookingDate: "2023-12-13T20:41:59.437482"
                      seat: 3
                      menu: true
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      tags:
        - booking
      summary: Registrar una nueva reserva
      operationId: postBooking
      requestBody:
        description: Información de la nueva reserva
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingIn'
      responses:
        '201':
          description: Reserva registrada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingOut'
              examples:
                booking1:
                  value:
                    - id: 50
                      number: "cc93b678-6e61-47b8-8707-8cd684542eab"
                      bookingDate: "2024-01-24T11:15:14.1501796"
                      row: 3
                      seat: 10
                      menu: false
                      showtimeIds: null
                booking2:
                  value:
                    - id: 60
                      number: "casjd83-6e61-47b8-8707-8cd6nashd"
                      bookingDate: "2024-01-24T11:15:14.1501796"
                      row: 7
                      seat: 20
                      menu: true
                      showtimeIds: null

        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      tags:
        - booking
      summary: Dar de baja una reserva
      operationId: deleteBooking
      parameters:
        - name: bookingId
          in: path
          description: Identificador de la reserva
          required: true
          schema:
            type: number
            format: int32
            example: 1
      responses:
        '204':
          description: Ok
        '404':
          description: No se ha encontrado la reserva
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar esta reserva"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    put:
      tags:
        - booking
      summary: Modifica una reserva
      description: Modifica los datos de una reserva concreta
      operationId: modifyBooking
      parameters:
        - name: bookingId
          in: path
          description: Identificador de la reserva
          required: true
          schema:
            type: number
            format: int32
            example: 1
      requestBody:
        description: Datos de reserva actualizados
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingIn'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingOut'
        '404':
          description: No se ha encontrado esta reserva
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar esta reserva"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /movie:
    get:
      tags:
        - movie
      summary: Listado de películas.
      description: Esta operación permite consultar el listado completo de películas con toda su información.
      parameters:
        - name: director
          in: query
          description: Nombre del director de la película
          required: true
          schema:
            type: string
            example: Juan
        - name: genre
          in: query
          description: Genero asociado a la película
          required: true
          schema:
            type: string
            example: Comedia
        - name: duration
          in: query
          description: Duración de la película en minutos
          required: true
          schema:
            type: number
            format: int32
            example: 90
      responses:
        '200':
          description: Devuelve la lista completa de películas registradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieOut'
              examples:
                movie1:
                  value:
                    - id: 10
                      title: Piratas del Caribe
                      director: Daniel
                      genre: Terror
                      duration: "90"
                      releaseDate: "2023-11-03"
                movie2:
                  value:
                    - id: 20
                      title: Gol
                      director: Sebastian
                      genre: comedia
                      duration: "100"
                      releaseDate: "2023-11-03"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      tags:
        - movie
      summary: Registrar una nueva película
      operationId: postMovie
      requestBody:
        description: Información de la nueva película
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieIn'
      responses:
        '201':
          description: Película registrada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieOut'
              examples:
                movie1:
                  value:
                    - id: 55
                      title: Viridiana
                      director: Julian
                      genre: Drama
                      duration: 95
                      releaseDate: "2023-11-03"
                movie2:
                  value:
                    - id: 55
                      title: Huertos
                      director: Sara
                      genre: Terror
                      duration: 95
                      releaseDate: "2023-11-03"

        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      tags:
        - movie
      summary: Dar de baja una película
      operationId: deleteMovie
      parameters:
        - name: movieId
          in: path
          description: Identificador de la película
          required: true
          schema:
            type: number
            format: int32
            example: 1
      responses:
        '204':
          description: Ok
        '404':
          description: No se ha encontrado la película
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar esta película"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    put:
      tags:
        - movie
      summary: Modifica una película
      description: Modifica los datos de una película concreta
      operationId: modifyMovie
      parameters:
        - name: movieId
          in: path
          description: Identificador de la película
          required: true
          schema:
            type: number
            format: int32
            example: 1
      requestBody:
        description: Datos de película actualizados
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieIn'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieOut'
        '404':
          description: No se ha encontrado esta película
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar esta película"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /cinema:
    get:
      tags:
        - cinema
      summary: Listado de cines.
      description: Esta operación permite consultar el listado completo de cines con toda su información.
      parameters:
        - name: name
          in: query
          description: Nombre del cine
          required: true
          schema:
            type: string
            example: Palafox
        - name: capacity
          in: query
          description: Capacidad de personas asociada al cine
          required: true
          schema:
            type: number
            format: int32
            example: 260
        - name: rating
          in: query
          description: Puntuación del cine
          required: true
          schema:
            type: number
            format: int32
            example: 7
      responses:
        '200':
          description: Devuelve la lista completa de cines registrados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CinemaOut'
              examples:
                cinema1:
                  value:
                    - id: 200
                      name: Palafox
                      capacity: "250"
                      latitude: "9.78438"
                      longitude: "5.895498934"
                      rating: "9.0"
                      openingDate: "2024-01-24"
                cinema2:
                  value:
                    - id: 201
                      name: Gran Casa
                      capacity: "280"
                      latitude: "10.78438"
                      longitude: "4.895498934"
                      rating: "5.0"
                      openingDate: "2023-01-23"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    post:
      tags:
        - cinema
      summary: Registrar un nuevo cine
      operationId: postCinema
      requestBody:
        description: Información del nuevo cine
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CinemaIn'
      responses:
        '201':
          description: Cine registrado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CinemaOut'
              examples:
                cinema1:
                  value:
                    - id: 300
                      name: Puerto Vencia
                      capacity: 250
                      latitude: "9.78438"
                      longitude: "5.895498934"
                      rating: "9.0"
                      openingDate: "2024-01-24"
                cinema2:
                  value:
                    - id: 4
                      name: Palafox
                      capacity: 180
                      latitude: "40.78438"
                      longitude: "20.895498934"
                      rating: "8.0"
                      openingDate: "2020-01-20"

        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    delete:
      tags:
        - cinema
      summary: Dar de baja un cine
      operationId: deleteCinema
      parameters:
        - name: CinemaId
          in: path
          description: Identificador del cine
          required: true
          schema:
            type: number
            format: int32
            example: 1
      responses:
        '204':
          description: Ok
        '404':
          description: No se ha encontrado al cine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar el cine"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

    put:
      tags:
        - cinema
      summary: Modifica un cine
      description: Modifica los datos de un cine concreto
      operationId: modifyCinema
      parameters:
        - name: cinemaId
          in: path
          description: Identificador del cine
          required: true
          schema:
            type: number
            format: int32
            example: 1
      requestBody:
        description: Datos del cine actualizados
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CinemaIn'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CinemaOut'
        '404':
          description: No se ha encontrado este cine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFound'
              example:
                internalError: 1
                message: "No se ha podido encontrar el usuario"
        '500':
          description: Error interno en el servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    BookingIn:
      type: object
      properties:
        user:
          type: integer
          format: int32
          example: 2
        showtime:
          type: integer
          format: int32
          example: 3
        bookingDate:
          type: string
          example: 2023-10-10
        numTickets:
          type: number
          format: int32
          example: 5
        customerName:
          type: string
          example: Daniel
    BookingOut:
      type: object
      properties:
        id:
          type: number
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/BookingIn'
    MovieIn:
      type: object
      properties:
        title:
          type: string
          example: Nombre de película
        director:
          type: string
          example: Director de la película
        genre:
          type: string
          example: comedia
        duration:
          type: number
          format: int32
          example: 120
        releaseDate:
          type: string
          example: 2022-05-18
    MovieOut:
      type: object
      properties:
        id:
          type: number
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/MovieIn'
    ShowtimeIn:
      type: object
      properties:
        screenNumber:
          type: number
          format: int32
          example: 1
        startTime:
          type: string
          example: 2023-11-14
        price:
          type: number
          format: float
          example: 4.5
        isSoldOut:
          type: boolean
        endTime:
          type: string
          example: 2023-12-20
    ShowtimeOut:
      type: object
      properties:
        id:
          type: number
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/ShowtimeIn'
    UserIn:
      type: object
      properties:
        username:
          type: string
          example: Danielfgrt
        password:
          type: string
        email:
          type: string
          example: dfguuuyy@gmail.com
        phone:
          type: number
          format: int32
          example: 675231890
    UserOut:
      type: object
      properties:
        id:
          type: number
          format: int32
          example: 1
        registrationDate:
          type: string
          example: 2023-04-10
      allOf:
        - $ref: '#/components/schemas/UserIn'
    CinemaIn:
      properties:
        name:
          type: string
          example: Palafox
        capacity:
          type: number
          format: int32
          example: 200
        latitude:
          type: number
          format: double
          example: 10.829389329
        longitude:
          type: number
          format: double
          example: 5.2390932
        openingDate:
          type: string
          example: 2020-05-01
        rating:
          type: number
          format: float
          example: 9.2
    CinemaOut:
      type: object
      properties:
        id:
          type: number
          format: int32
          example: 1
      allOf:
        - $ref: '#/components/schemas/CinemaIn'
    ErrorResponse:
      properties:
        internalError:
          type: number
          format: int32
        message:
          type: string
      type: object
    ResourceNotFound:
      allOf:
        - type: object
        - $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      type: object
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
      example:
        internalError: 500
        message: "Internal Server Error"